/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiReportRouteImport } from './routes/ai-report'
import { Route as ApiDiagnosticRouteImport } from './routes/api/diagnostic'
import { Route as ApiBinanceSpotPriceRouteImport } from './routes/api/binance/spot-price'
import { Route as ApiPublicCronRouteImport } from './routes/api/public/cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReportRoute = AiReportRouteImport.update({
  id: '/ai-report',
  path: '/ai-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticRoute = ApiDiagnosticRouteImport.update({
  id: '/api/diagnostic',
  path: '/api/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceSpotPriceRoute = ApiBinanceSpotPriceRouteImport.update({
  id: '/api/binance/spot-price',
  path: '/api/binance/spot-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRoute = ApiPublicCronRouteImport.update({
  id: '/api/public/cron',
  path: '/api/public/cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-report': typeof AiReportRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
  '/api/binance/spot-price': typeof ApiBinanceSpotPriceRoute
  '/api/public/cron': typeof ApiPublicCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-report': typeof AiReportRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
  '/api/binance/spot-price': typeof ApiBinanceSpotPriceRoute
  '/api/public/cron': typeof ApiPublicCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-report': typeof AiReportRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
  '/api/binance/spot-price': typeof ApiBinanceSpotPriceRoute
  '/api/public/cron': typeof ApiPublicCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-report'
    | '/api/diagnostic'
    | '/api/binance/spot-price'
    | '/api/public/cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-report'
    | '/api/diagnostic'
    | '/api/binance/spot-price'
    | '/api/public/cron'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-report'
    | '/api/diagnostic'
    | '/api/binance/spot-price'
    | '/api/public/cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiReportRoute: typeof AiReportRoute
  ApiDiagnosticRoute: typeof ApiDiagnosticRoute
  ApiBinanceSpotPriceRoute: typeof ApiBinanceSpotPriceRoute
  ApiPublicCronRoute: typeof ApiPublicCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-report': {
      id: '/ai-report'
      path: '/ai-report'
      fullPath: '/ai-report'
      preLoaderRoute: typeof AiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostic': {
      id: '/api/diagnostic'
      path: '/api/diagnostic'
      fullPath: '/api/diagnostic'
      preLoaderRoute: typeof ApiDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance/spot-price': {
      id: '/api/binance/spot-price'
      path: '/api/binance/spot-price'
      fullPath: '/api/binance/spot-price'
      preLoaderRoute: typeof ApiBinanceSpotPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron': {
      id: '/api/public/cron'
      path: '/api/public/cron'
      fullPath: '/api/public/cron'
      preLoaderRoute: typeof ApiPublicCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiReportRoute: AiReportRoute,
  ApiDiagnosticRoute: ApiDiagnosticRoute,
  ApiBinanceSpotPriceRoute: ApiBinanceSpotPriceRoute,
  ApiPublicCronRoute: ApiPublicCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
