create table if not exists public.strategy_shadow_diagnostics (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  symbol text not null,
  strategy_preset text,
  strategy_updated_at timestamptz,
  whale_weight numeric not null,
  technicals_weight numeric not null,
  prediction_weight numeric not null,
  council_weight numeric not null,
  current_score numeric not null,
  current_recommendation text not null,
  shadow_score numeric not null,
  shadow_confidence numeric not null,
  shadow_recommendation text not null
);

create index if not exists strategy_shadow_diagnostics_created_at_idx
  on public.strategy_shadow_diagnostics (created_at desc);

create index if not exists strategy_shadow_diagnostics_symbol_idx
  on public.strategy_shadow_diagnostics (symbol, created_at desc);

alter table public.strategy_shadow_diagnostics enable row level security;
